✅ Started W&B orchestrator run: orchestrator_20250620_222256
✅ Set MLflow experiment to: 'MLOps-Group-Project-Experiment'
▶️  Running step: 'data_load'...
2025/06/20 22:22:58 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 22:22:58 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmp_2rhedw1 for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 22:22:58 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/data_load/run.py' in run with ID '8a6ad9312851449986367d69d4101436' ===
2025/06/20 22:23:04 ERROR mlflow.projects: === Run (ID '8a6ad9312851449986367d69d4101436') interrupted, cancelling run ===
Traceback (most recent call last):
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/main.py", line 190, in <module>
    main()
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/main.py", line 141, in main
    mlflow.run(".", entry_point=step, parameters=params)
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 374, in run
    _wait_for(submitted_run_obj)
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/mlflow/projects/__init__.py", line 386, in _wait_for
    if submitted_run_obj.wait():
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/site-packages/mlflow/projects/submitted_run.py", line 74, in wait
    return self.command_proc.wait() == 0
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/subprocess.py", line 1222, in wait
    self._wait(timeout=sigint_timeout)
  File "/Users/aviv/Applications/anaconda3/envs/crypto_mlflow_env/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt
