✅ Started W&B orchestrator run: orchestrator_20250620_191430
✅ Set MLflow experiment to: 'MLOps-Group-Project-Experiment'
▶️  Running step: 'data_load'...
2025/06/20 19:14:32 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:14:32 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmp2v_y31mb for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:14:32 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/data_load/run.py' in run with ID '95865be8aaf04069a349439e8f8fc42d' ===
2025/06/20 19:14:59 INFO mlflow.projects: === Run (ID '95865be8aaf04069a349439e8f8fc42d') succeeded ===
✅ Step 'data_load' finished.
▶️  Running step: 'data_validation'...
2025/06/20 19:15:00 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:15:00 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmphokh4vex for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:15:00 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/data_validation/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/data/raw/raw_data.csv'' in run with ID '91f9873fdc8e475a836a87ee1096d7f4' ===
2025/06/20 19:15:06 INFO mlflow.projects: === Run (ID '91f9873fdc8e475a836a87ee1096d7f4') succeeded ===
✅ Step 'data_validation' finished.
▶️  Running step: 'features'...
2025/06/20 19:15:07 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:15:07 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmp8oi38gr7 for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:15:07 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/features/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/./data/processed/futures_data_processed_.csv'' in run with ID '2ba47b2ec5ce4ecfb0d6b9ffd71f7ba1' ===
2025/06/20 19:15:13 INFO mlflow.projects: === Run (ID '2ba47b2ec5ce4ecfb0d6b9ffd71f7ba1') succeeded ===
✅ Step 'features' finished.
▶️  Running step: 'preprocess'...
2025/06/20 19:15:14 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:15:14 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpss0kq8fn for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:15:14 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/preproccess/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/data/processed/feature_engineered_data.csv'' in run with ID '495c82bda6154afc90c1c642dc74a8de' ===
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/main.py", line 130, in main
    mlflow.run(".", entry_point=step, parameters=params)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 374, in run
    _wait_for(submitted_run_obj)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 391, in _wait_for
    raise ExecutionException(f"Run (ID '{run_id}') failed")
mlflow.exceptions.ExecutionException: Run (ID '495c82bda6154afc90c1c642dc74a8de') failed

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
