✅ Started W&B orchestrator run: orchestrator_20250620_192228
✅ Set MLflow experiment to: 'MLOps-Group-Project-Experiment'
▶️  Running step: 'data_load'...
2025/06/20 19:22:31 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:22:31 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpfcltpxs9 for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:22:31 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/data_load/run.py' in run with ID '34a62daf50e6449399cc7ae24beb5705' ===
2025/06/20 19:23:06 INFO mlflow.projects: === Run (ID '34a62daf50e6449399cc7ae24beb5705') succeeded ===
✅ Step 'data_load' finished.
▶️  Running step: 'data_validation'...
2025/06/20 19:23:07 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:23:07 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmp7h0j70oa for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:23:07 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/data_validation/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/data/raw/raw_data.csv'' in run with ID 'c248b25dcb64449980d42334b98f09ac' ===
2025/06/20 19:23:13 INFO mlflow.projects: === Run (ID 'c248b25dcb64449980d42334b98f09ac') succeeded ===
✅ Step 'data_validation' finished.
▶️  Running step: 'features'...
2025/06/20 19:23:14 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:23:14 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpneqn8kw4 for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:23:14 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/features/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/./data/processed/futures_data_processed_.csv'' in run with ID 'c36c15fd328e4aa0abc761447480c7ee' ===
2025/06/20 19:23:20 INFO mlflow.projects: === Run (ID 'c36c15fd328e4aa0abc761447480c7ee') succeeded ===
✅ Step 'features' finished.
▶️  Running step: 'preprocess'...
2025/06/20 19:23:21 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:23:21 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmp92c_65ls for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:23:21 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/preproccess/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/data/processed/feature_engineered_data.csv'' in run with ID '85aa4ed861674119bc97bb7bed70b4f3' ===
2025/06/20 19:23:27 INFO mlflow.projects: === Run (ID '85aa4ed861674119bc97bb7bed70b4f3') succeeded ===
✅ Step 'preprocess' finished.
▶️  Running step: 'models'...
2025/06/20 19:23:28 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:23:28 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpwwgtbw6h for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:23:28 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/models/run.py --input-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/data/processed/training_data'' in run with ID '17105fa255124798bb3bea2c4ec2870f' ===
2025/06/20 19:23:33 INFO mlflow.projects: === Run (ID '17105fa255124798bb3bea2c4ec2870f') succeeded ===
✅ Step 'models' finished.
▶️  Running step: 'evaluation'...
2025/06/20 19:23:34 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:23:34 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmp5k6foesq for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:23:34 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 src/mlops/evaluation/run.py --model-artifact '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/models/logistic_regression.pkl' --test-data-path '/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/data/processed/training_data'' in run with ID '892528267e13465ead16dddc3046a8f1' ===
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/main.py", line 141, in main
    mlflow.run(".", entry_point=step, parameters=params)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 374, in run
    _wait_for(submitted_run_obj)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 391, in _wait_for
    raise ExecutionException(f"Run (ID '{run_id}') failed")
mlflow.exceptions.ExecutionException: Run (ID '892528267e13465ead16dddc3046a8f1') failed

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
